# api call for signup
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username":"user4",
    "password":"user123",
    "email":"user@gmail.com"
}


# api call for create employee
###
POST http://127.0.0.1:8000/employee/
Content-Type: application/json
Authorization: Basic user:user123

{
    "name": "Alice Thompson",
    "department": "Engineering",
    "designation": "Senior Backend Developer",
    "salary": 95000,
    "email": "alice.t@company.com",
    "date_of_joining": "2023-03-15"
}


# api call for list employees
###
GET http://127.0.0.1:8000/employee/
Accept: application/json
Content-Type: application/json
Authorization: Basic user:user123
